### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Hipisuaw** [MrDemonWolf/share-mrdemonwolf-me#32]
How to install it with FTP - WinSCP? Downloaded files, but what now?

**Comment by nathanhenniges** [comment]
For starters please make sure you have NodeJS installed on the server host.

You can run these commands to see if you have NPM and NodeJS Installed.
```sh
$ node
```
```sh
$ npm
```

If any output is returned then you are in good shape.  Do make sure the node version is version 10+ as that's a requirement. 

If no output then look [here](https://nodejs.org/en/download/) on how to install NodeJS on your OS.

Once that's done you will need to create a account on [sendgrid](https://www.sendgrid.com) and then get an API key following these steps [here](https://sendgrid.com/docs/ui/account-and-settings/api-keys/)

You will need to set up domain and more.  Which they tell you in detail how to do.

Once that's all good.  

You can follow the repo steps [here](https://github.com/MrDemonWolf/share-mrdemonwolf-me#edit-the-envexample-with-basic-config)

If you need any more help you can join my discord and I can try to help you the best I can
[Discord Invite](https://l.demonwolfdev.com/discord)

**Comment by nathanhenniges** [comment]
Said he had shared hosting so it would not work.  Closing issue.
