### ISSUE TITLE
"Connection Strategy Not Found"

### ISSUE THREAD

**Issue by Xeratuhl** [MrDemonWolf/share-mrdemonwolf-me#53]
While attempting to get this up and running I keep getting an error on line 113 of index.js simply said as "Connection strategy not found"
Further investigation links it to a line in connect-mongo about MongoStore. Not entirely sure if this is isolated to just me or not, any suggestions would be appreciated though.

**Comment by nathanhenniges** [comment]
Did you download from the relases page [here](https://github.com/MrDemonWolf/share-mrdemonwolf-me/releases)

**Comment by Xeratuhl** [comment]
With some small testing I figured out what was happening. Everything was configured properly but the .env file was not just `.env` instead I had it as `conf.env` which seems to cause it to throw that error mentioned above.

**Comment by nathanhenniges** [comment]
You will have to change that in the database it self by adding `isAdmin: true` in version 4 this has been added.

**Comment by Xeratuhl** [comment]
That would be appreciated.

**Comment by nathanhenniges** [comment]
As you got this fixed.  Am closing this issue as resolved.   Feel free to reopen if you have issue again.
