### ISSUE TITLE
[Seemingly a bug, fix included] Time failing to update in DB and Uploads

### ISSUE THREAD

**Issue by Xeratuhl** [MrDemonWolf/share-mrdemonwolf-me#54]
Hey I noticed a small bug when you would upload files the time would never update.
For example the time would be 3:08 AM and the process started at 3:01 and it would never update from 3:01 until MongoDB or it was restarted.

I'm not sure if this was isolated to just me or not (Tested both 3.1.1 and current one in master)
If it is indeed a wide spread bug the problem is caused by the mongoose schema ``upload.js`` in Models.
``  createdAt: {
    type: Date,
    default: Date.now()
  }``
For some reason if you have () on the end of Date.now() it seems to never update but if you remove () then it updates every single time. So the simple fix for it for me was removing () and just having it as:
``  createdAt: {
    type: Date,
    default: Date.now
  }``

Edit:
After some research I found this.

> What's going on is that you're calling Date.now() at the time the schema is defined to set the default value for createdAt, and then that value is being used for the default until the next time your app is restarted. 
> Instead, you want to set the default value to the Date.now function itself so that it will be called each time a new doc is created:

**Comment by nathanhenniges** [comment]
Thanks for reporting this issue.  Will look into this and if needed make the change to fix it.  Going to set up a quick hotfix.  In version 4.0.0 this should not be an issue anymore.

**Comment by nathanhenniges** [comment]
@Xeratuhl Added the hotfix you can download it [here](https://github.com/MrDemonWolf/share-mrdemonwolf-me/releases/tag/3.1.2)
